
   `undef APB_DATA_WIDTH
   `undef APB_DATA_WIDTH_32
   `undef APB_DATA_WIDTH_NOT_8
   `undef ASYNC
   `undef DWC_BCM06_NO_DIAG_N
   `undef DWC_NO_CDC_INIT
   `undef DWC_NO_TST_MODE
   `undef DW_HOLD_MUX_DELAY
   `undef DW_SETUP_MUX_DELAY
   `undef ENCODED_APB_DATA_WIDTH
   `undef ENCODED_IC_RX_BUFFER_DEPTH
   `undef ENCODED_IC_TX_BUFFER_DEPTH
   `undef HC_REG_TIMEOUT_VALUE
   `undef I2C_DYNAMIC_TAR_UPDATE
   `undef IC_10BITADDR_MASTER
   `undef IC_10BITADDR_SLAVE
   `undef IC_ACK_GENERAL_CALL_OS
   `undef IC_ACK_GENERAL_CALL_RS
   `undef IC_ADDR_SLICE_LHS
   `undef IC_ADD_ENCODED_PARAMS
   `undef IC_AVOID_RX_FIFO_FLUSH_ON_TX_ABRT
   `undef IC_BUS_CLEAR_FEATURE
   `undef IC_CAP_LOADING
   `undef IC_CLK_FREQ
   `undef IC_CLK_FREQ_OPTIMIZATION
   `undef IC_CLK_TYPE
   `undef IC_CLOCK_PERIOD
   `undef IC_CLR_ACTIVITY_OS
   `undef IC_CLR_ACTIVITY_RS
   `undef IC_CLR_GEN_CALL_OS
   `undef IC_CLR_GEN_CALL_RS
   `undef IC_CLR_INTR_OS
   `undef IC_CLR_INTR_RS
   `undef IC_CLR_RD_REQ_OS
   `undef IC_CLR_RD_REQ_RS
   `undef IC_CLR_RESTART_DET_RS
   `undef IC_CLR_RX_DONE_OS
   `undef IC_CLR_RX_DONE_RS
   `undef IC_CLR_RX_OVER_OS
   `undef IC_CLR_RX_OVER_RS
   `undef IC_CLR_RX_UNDER_OS
   `undef IC_CLR_RX_UNDER_RS
   `undef IC_CLR_START_DET_OS
   `undef IC_CLR_START_DET_RS
   `undef IC_CLR_STOP_DET_OS
   `undef IC_CLR_STOP_DET_RS
   `undef IC_CLR_TX_ABRT_OS
   `undef IC_CLR_TX_ABRT_RS
   `undef IC_CLR_TX_OVER_OS
   `undef IC_CLR_TX_OVER_RS
   `undef IC_COMP_PARAM_1_IN
   `undef IC_COMP_PARAM_1_OS
   `undef IC_COMP_PARAM_UFM_1_IN
   `undef IC_COMP_TYPE_OS
   `undef IC_COMP_VERSION_OS
   `undef IC_CON_IN
   `undef IC_CON_OS
   `undef IC_CON_RS
   `undef IC_DATA_CMD_OS
   `undef IC_DATA_CMD_RS
   `undef IC_DATA_FIFO_RS
   `undef IC_DATA_RS
   `undef IC_DATA_TX_CMD_RS
   `undef IC_DEFAULT_ACK_GENERAL_CALL
   `undef IC_DEFAULT_FS_SPKLEN
   `undef IC_DEFAULT_HS_SPKLEN
   `undef IC_DEFAULT_SDA_HOLD
   `undef IC_DEFAULT_SDA_RX_HOLD
   `undef IC_DEFAULT_SDA_SETUP
   `undef IC_DEFAULT_SDA_TX_HOLD
   `undef IC_DEFAULT_SLAVE_ADDR
   `undef IC_DEFAULT_TAR_SLAVE_ADDR
   `undef IC_DEFAULT_UFM_SPKLEN
   `undef IC_DEVICE_ID
   `undef IC_DEVICE_ID_BYTE
   `undef IC_DEVICE_ID_VALUE
   `undef IC_DMA_CR_OS
   `undef IC_DMA_CR_RS
   `undef IC_DMA_RDLR_OS
   `undef IC_DMA_RDLR_RS
   `undef IC_DMA_TDLR_OS
   `undef IC_DMA_TDLR_RS
   `undef IC_EMPTYFIFO_HOLD_MASTER_EN
   `undef IC_ENABLE_IN
   `undef IC_ENABLE_OS
   `undef IC_ENABLE_RS
   `undef IC_ENABLE_RS_INT
   `undef IC_ENABLE_STATUS_OS
   `undef IC_ENABLE_STATUS_RS
   `undef IC_FIRST_DATA_BYTE_STATUS
   `undef IC_FS_HCNT_IN
   `undef IC_FS_HCNT_OS
   `undef IC_FS_HCNT_RS
   `undef IC_FS_LCNT_IN
   `undef IC_FS_LCNT_OS
   `undef IC_FS_LCNT_RS
   `undef IC_FS_MAX_SPKLEN
   `undef IC_FS_SCL_HIGH_COUNT
   `undef IC_FS_SCL_LOW_COUNT
   `undef IC_FS_SPKLEN_LO_LIMIT
   `undef IC_FS_SPKLEN_OS
   `undef IC_FS_SPKLEN_RS
   `undef IC_GENERAL_CALL
   `undef IC_HAS_APB3_IF_SIGNALS
   `undef IC_HAS_ASYNC_CLK
   `undef IC_HAS_ASYNC_FIFO
   `undef IC_HAS_DMA
   `undef IC_HAS_POSITIVE_REG_TIMEOUT_WIDTH
   `undef IC_HAS_SLVERR_RESP_EN
   `undef IC_HCNT_LO_LIMIT
   `undef IC_HC_COUNT_VALUES
   `undef IC_HIGHSPEED_MODE_EN
   `undef IC_HS_CODE
   `undef IC_HS_HCNT_IN
   `undef IC_HS_HCNT_OS
   `undef IC_HS_HCNT_RS
   `undef IC_HS_LCNT_IN
   `undef IC_HS_LCNT_OS
   `undef IC_HS_LCNT_RS
   `undef IC_HS_MADDR_IN
   `undef IC_HS_MADDR_OS
   `undef IC_HS_MADDR_RS
   `undef IC_HS_MASTER_CODE
   `undef IC_HS_MAX_SPKLEN
   `undef IC_HS_SCL_HIGH_COUNT
   `undef IC_HS_SCL_LOW_COUNT
   `undef IC_HS_SPKLEN_LO_LIMIT
   `undef IC_HS_SPKLEN_OS
   `undef IC_HS_SPKLEN_RS
   `undef IC_INTR_IO
   `undef IC_INTR_MASK_OS
   `undef IC_INTR_MASK_RS
   `undef IC_INTR_POL
   `undef IC_INTR_STAT_OS
   `undef IC_INTR_STAT_RS
   `undef IC_LCNT_LO_LIMIT
   `undef IC_MASTER_MODE
   `undef IC_MAX_SPEED_MODE
   `undef IC_OPTIONAL_SAR
   `undef IC_OPTIONAL_SAR_DEFAULT
   `undef IC_PERSISTANT_SLV_ADDR_DEFAULT
   `undef IC_RAND_SEED
   `undef IC_RAW_INTR_STAT_OS
   `undef IC_RAW_INTR_STAT_RS
   `undef IC_RESTART_EN
   `undef IC_RUN_FOR_ONE_HOUR
   `undef IC_RXFLR_OS
   `undef IC_RX_BUFFER_DEPTH
   `undef IC_RX_BUFFER_MOD_DEPTH
   `undef IC_RX_FULL_GEN_NACK
   `undef IC_RX_FULL_HLD_BUS_EN
   `undef IC_RX_TL
   `undef IC_RX_TL_IN
   `undef IC_RX_TL_OS
   `undef IC_RX_TL_RS
   `undef IC_SAR_IN
   `undef IC_SAR_OPT_IN
   `undef IC_SAR_OPT_RS
   `undef IC_SAR_OS
   `undef IC_SAR_RS
   `undef IC_SCL_SDA_TIMEOUT_RS
   `undef IC_SCL_STUCK_TIMEOUT_DEFAULT
   `undef IC_SDA_HOLD_OS
   `undef IC_SDA_HOLD_RS
   `undef IC_SDA_RX_HOLD_RS
   `undef IC_SDA_SETUP_OS
   `undef IC_SDA_SETUP_RS
   `undef IC_SDA_STUCK_TIMEOUT_DEFAULT
   `undef IC_SDA_TX_HOLD_RS
   `undef IC_SLAVE_DISABLE
   `undef IC_SLV_ADDR_10BIT
   `undef IC_SLV_DATA_NACK_ONLY
   `undef IC_SLV_DATA_NACK_ONLY_RS
   `undef IC_SLV_RESTART_DET_EN
   `undef IC_SMBUS
   `undef IC_SMBUS_ARP
   `undef IC_SMBUS_ASSGN_ADDR_CMD
   `undef IC_SMBUS_CLK_LOW_MEXT_DEFAULT
   `undef IC_SMBUS_CLK_LOW_SEXT_DEFAULT
   `undef IC_SMBUS_CON_EXT_RS
   `undef IC_SMBUS_DEVICE_DEFAULT_ADDRESS
   `undef IC_SMBUS_GEN_GET_UDID_CMD
   `undef IC_SMBUS_GEN_RESET_CMD
   `undef IC_SMBUS_HAS_UDID_HC
   `undef IC_SMBUS_HOST_SLAVE_ADDRESS
   `undef IC_SMBUS_INTR_RS
   `undef IC_SMBUS_PREPARE_TO_ARP_CMD
   `undef IC_SMBUS_RD_DEVICE_DEFAULT_ADDRESS
   `undef IC_SMBUS_RST_IDLE_CNT_DEFAULT
   `undef IC_SMBUS_RST_IDLE_CNT_RS
   `undef IC_SMBUS_SUSPEND_ALERT
   `undef IC_SMBUS_SUS_ALERT_RS
   `undef IC_SMBUS_TIMEOUT_RS
   `undef IC_SMBUS_UDID_BYTE_COUNT
   `undef IC_SMBUS_UDID_BYTE_COUNT_LOG2
   `undef IC_SMBUS_UDID_BYTE_COUNT_PLS1
   `undef IC_SMBUS_UDID_HC
   `undef IC_SMBUS_UDID_LSB_DEFAULT
   `undef IC_SMBUS_UDID_LSB_RS
   `undef IC_SMBUS_UDID_MSB
   `undef IC_SMBUS_UDID_RS
   `undef IC_SPEED_SIM
   `undef IC_SPKLEN_RS
   `undef IC_SRESET_RS
   `undef IC_SS_HCNT_IN
   `undef IC_SS_HCNT_OS
   `undef IC_SS_HCNT_RS
   `undef IC_SS_LCNT_IN
   `undef IC_SS_LCNT_OS
   `undef IC_SS_LCNT_RS
   `undef IC_SS_SCL_HIGH_COUNT
   `undef IC_SS_SCL_LOW_COUNT
   `undef IC_START_BYTE
   `undef IC_STATUS_IN
   `undef IC_STATUS_OS
   `undef IC_STATUS_RS
   `undef IC_STAT_FOR_CLK_STRETCH
   `undef IC_STOP_DET_IF_MASTER_ACTIVE
   `undef IC_SYNC_DEPTH
   `undef IC_TAR_IN
   `undef IC_TAR_IN_RAL
   `undef IC_TAR_OS
   `undef IC_TAR_RS
   `undef IC_TAR_RS_INT
   `undef IC_TXFLR_OS
   `undef IC_TX_ABRT_SOURCE_OS
   `undef IC_TX_ABRT_SOURCE_RS
   `undef IC_TX_BUFFER_DEPTH
   `undef IC_TX_BUFFER_MOD_DEPTH
   `undef IC_TX_CMD_BLOCK
   `undef IC_TX_CMD_BLOCK_DEFAULT
   `undef IC_TX_TL
   `undef IC_TX_TL_IN
   `undef IC_TX_TL_OS
   `undef IC_TX_TL_RS
   `undef IC_UFM_SCL_HIGH_COUNT
   `undef IC_UFM_SCL_LOW_COUNT
   `undef IC_UFM_TBUF_CNT_DEFAULT
   `undef IC_ULTRA_FAST_MODE
   `undef IC_USE_COUNTS
   `undef IC_VERIF_EN
   `undef IC_VERSION_ID
   `undef IC_VERSION_ID_IN
   `undef IC_VERSION_ID_RS
   `undef IC_VMT_MODEL_INCLUDED
   `undef IDENT
   `undef MAX_APB_DATA_WIDTH
   `undef POW_2_REG_TIMEOUT_WIDTH
   `undef REG_TIMEOUT_RST_OS
   `undef REG_TIMEOUT_VALUE
   `undef REG_TIMEOUT_WIDTH
   `undef RM_BCM01
   `undef RM_BCM02
   `undef RM_BCM03
   `undef RM_BCM05
   `undef RM_BCM05_ATV
   `undef RM_BCM06
   `undef RM_BCM06_ATV
   `undef RM_BCM07
   `undef RM_BCM07_ATV
   `undef RM_BCM08
   `undef RM_BCM09
   `undef RM_BCM09_DP
   `undef RM_BCM09_ECC
   `undef RM_BCM10
   `undef RM_BCM11
   `undef RM_BCM12
   `undef RM_BCM15
   `undef RM_BCM16
   `undef RM_BCM21
   `undef RM_BCM21_A
   `undef RM_BCM21_ATV
   `undef RM_BCM21_CG
   `undef RM_BCM22
   `undef RM_BCM22_ATV
   `undef RM_BCM23
   `undef RM_BCM23_ATV
   `undef RM_BCM24
   `undef RM_BCM24_AP
   `undef RM_BCM25
   `undef RM_BCM25_ATV
   `undef RM_BCM26
   `undef RM_BCM27
   `undef RM_BCM28
   `undef RM_BCM29
   `undef RM_BCM30
   `undef RM_BCM31
   `undef RM_BCM32
   `undef RM_BCM35
   `undef RM_BCM36
   `undef RM_BCM36_NHS
   `undef RM_BCM37
   `undef RM_BCM38
   `undef RM_BCM38_ADP
   `undef RM_BCM38_AP
   `undef RM_BCM38_ECC
   `undef RM_BCM39
   `undef RM_BCM40
   `undef RM_BCM41
   `undef RM_BCM42
   `undef RM_BCM43
   `undef RM_BCM43_NRO
   `undef RM_BCM44
   `undef RM_BCM44_NRO
   `undef RM_BCM46_A
   `undef RM_BCM46_AA
   `undef RM_BCM46_B
   `undef RM_BCM46_C
   `undef RM_BCM46_D
   `undef RM_BCM46_E
   `undef RM_BCM47
   `undef RM_BCM48
   `undef RM_BCM48_DM
   `undef RM_BCM48_SV
   `undef RM_BCM49
   `undef RM_BCM49_SV
   `undef RM_BCM50
   `undef RM_BCM51
   `undef RM_BCM52
   `undef RM_BCM53
   `undef RM_BCM54
   `undef RM_BCM55
   `undef RM_BCM56
   `undef RM_BCM57
   `undef RM_BCM58
   `undef RM_BCM59
   `undef RM_BCM60
   `undef RM_BCM62
   `undef RM_BCM63
   `undef RM_BCM64
   `undef RM_BCM64_TD
   `undef RM_BCM65
   `undef RM_BCM65_ATV
   `undef RM_BCM65_TD
   `undef RM_BCM66
   `undef RM_BCM71
   `undef RM_BCM72
   `undef RM_BCM73
   `undef RM_BCM74
   `undef RM_BCM76
   `undef RM_BCM85
   `undef RM_BCM86
   `undef RM_BCM87
   `undef RM_BCM90
   `undef RM_BCM95
   `undef RM_BCM95_E
   `undef RM_BCM95_I
   `undef RM_BCM95_IE
   `undef RM_BCM98
   `undef RM_BCM99
   `undef RM_BCM99_N
   `undef RM_BVM01
   `undef RM_BVM02
   `undef RM_SVA01
   `undef RM_SVA02
   `undef RM_SVA03
   `undef RM_SVA04
   `undef RM_SVA05
   `undef RM_SVA06
   `undef RM_SVA07
   `undef RM_SVA99
   `undef RX_ABW
   `undef RX_ABW_P1
   `undef SLAVE_INTERFACE_TYPE
   `undef SLVERR_RESP_EN
   `undef SMB_ALERT_ADDRESS
   `undef SYNC
   `undef TX_ABW
   `undef TX_ABW_P1
`define cb_dummy_parameter_definition 1
`undef  cb_dummy_parameter_definition
