// This file was automatically generated by coreConsultant (version N-2017.12-SP2).
// 
// FILENAME : /home/liubin/project/dw_iip/i_i2c_1/export/DW_apb_i2c_inst.v
// DATE : 05/19/20 20:17:53
// ABSTRACT : Verilog Testbench template (Example design instantiation).
// 

module DW_apb_i2c_inst (
                        );


   wire         dut_ic_start_det_intr;
   wire         dut_ic_stop_det_intr;
   wire         dut_ic_activity_intr;
   wire         dut_ic_rx_done_intr;
   wire         dut_ic_tx_abrt_intr;
   wire         dut_ic_rd_req_intr;
   wire         dut_ic_tx_empty_intr;
   wire         dut_ic_tx_over_intr;
   wire         dut_ic_rx_full_intr;
   wire         dut_ic_rx_over_intr;
   wire         dut_ic_rx_under_intr;
   wire         dut_ic_gen_call_intr;
   wire         dut_ic_current_src_en;
   wire         dut_pclk;
   wire         dut_presetn;
   wire         dut_psel;
   wire         dut_penable;
   wire         dut_pwrite;
   wire [7:0]   dut_paddr;
   wire [31:0]  dut_pwdata;
   wire [31:0]  dut_prdata;
   wire         dut_pready;
   wire         dut_pslverr;
   wire         dut_ic_clk;
   wire         dut_ic_clk_in_a;
   wire         dut_ic_data_in_a;
   wire         dut_ic_rst_n;
   wire         dut_debug_s_gen;
   wire         dut_debug_p_gen;
   wire         dut_debug_data;
   wire         dut_debug_addr;
   wire         dut_debug_rd;
   wire         dut_debug_wr;
   wire         dut_debug_hs;
   wire         dut_debug_master_act;
   wire         dut_debug_slave_act;
   wire         dut_debug_addr_10bit;
   wire [4:0]   dut_debug_mst_cstate;
   wire [3:0]   dut_debug_slv_cstate;
   wire         dut_ic_clk_oe;
   wire         dut_ic_data_oe;
   wire         dut_ic_en;

   DW_apb_i2c dut
      (.ic_start_det_intr     (dut_ic_start_det_intr),
       .ic_stop_det_intr      (dut_ic_stop_det_intr),
       .ic_activity_intr      (dut_ic_activity_intr),
       .ic_rx_done_intr       (dut_ic_rx_done_intr),
       .ic_tx_abrt_intr       (dut_ic_tx_abrt_intr),
       .ic_rd_req_intr        (dut_ic_rd_req_intr),
       .ic_tx_empty_intr      (dut_ic_tx_empty_intr),
       .ic_tx_over_intr       (dut_ic_tx_over_intr),
       .ic_rx_full_intr       (dut_ic_rx_full_intr),
       .ic_rx_over_intr       (dut_ic_rx_over_intr),
       .ic_rx_under_intr      (dut_ic_rx_under_intr),
       .ic_gen_call_intr      (dut_ic_gen_call_intr),
       .ic_current_src_en     (dut_ic_current_src_en),
       .pclk                  (dut_pclk),
       .presetn               (dut_presetn),
       .psel                  (dut_psel),
       .penable               (dut_penable),
       .pwrite                (dut_pwrite),
       .paddr                 (dut_paddr),
       .pwdata                (dut_pwdata),
       .prdata                (dut_prdata),
       .pready                (dut_pready),
       .pslverr               (dut_pslverr),
       .ic_clk                (dut_ic_clk),
       .ic_clk_in_a           (dut_ic_clk_in_a),
       .ic_data_in_a          (dut_ic_data_in_a),
       .ic_rst_n              (dut_ic_rst_n),
       .debug_s_gen           (dut_debug_s_gen),
       .debug_p_gen           (dut_debug_p_gen),
       .debug_data            (dut_debug_data),
       .debug_addr            (dut_debug_addr),
       .debug_rd              (dut_debug_rd),
       .debug_wr              (dut_debug_wr),
       .debug_hs              (dut_debug_hs),
       .debug_master_act      (dut_debug_master_act),
       .debug_slave_act       (dut_debug_slave_act),
       .debug_addr_10bit      (dut_debug_addr_10bit),
       .debug_mst_cstate      (dut_debug_mst_cstate),
       .debug_slv_cstate      (dut_debug_slv_cstate),
       .ic_clk_oe             (dut_ic_clk_oe),
       .ic_data_oe            (dut_ic_data_oe),
       .ic_en                 (dut_ic_en));

endmodule
